name: github-ci-cd
run-name: github-ci-cd is running by ${{ github.actor }} 
on: 
  workflow_dispatch:
  push:
    tags: 
      - v1.*

env:
  TAG: echo "${GITHUB_REF}" | sed -n 's|refs/tags/\(.*\)|\1|p'

jobs:
  dockerCI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show notification
        run: echo "pushing tag ${{ github.event.ref }}...!" 
             
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0
           
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0
         
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: ed358/web-app:${{ env.TAG }}
 
  kubernetesCI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'edlay17/config-kubernetes'

      - name: Show notification
        run: echo "updating image to ed358/web-app:$TAG...!" 

      - name: Configure Git Access
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Modify Manifests
        run: |
          sed -i 's|ed358/web-app:latest|ed358/web-app:${{ env.TAG }}|' deployment.yaml
          git add deployment.yaml
          git commit -m "Update Docker image version in deployment.yaml"
          git push
