name: github-ci-cd
run-name: ${{ github.actor }} is running 
on: 
  push:
    branches:
      - main
    tags: 
      - v1.*
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!