name: github-ci-cd
run-name: github-ci-cd is running by ${{ github.actor }} 
on: 
  workflow_dispatch:
  push:
    tags: 
      - v1.*

jobs:
  setTAG:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - id: tag
        run: |
          echo tag=$(echo "${{ github.event.ref }}" | sed 's/refs\/tags\///') >> "$GITHUB_OUTPUT"

  dockerCI:
    runs-on: ubuntu-latest

    needs: setTAG

    steps:
      - uses: actions/checkout@v4
             
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0
           
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0
         
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Start of building and pushing
        run: echo "bulding and pusing ${{ needs.setTag.outputs.tag }} tag"
         
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: ed358/web-app:${{ needs.setTag.outputs.tag }}
 
  kubernetesCI:
    runs-on: ubuntu-latest

    needs: [setTAG, dockerCI]

    steps:
      - uses: actions/checkout@v4
        with:
          repository: edlay17/config-kubernetes
          token: ${{ secrets.GIT_PERSONAL_TOKEN }}

      - name: Start of updating image's tag
        run: echo "updating image to ed358/web-app:${{ needs.setTag.outputs.tag }}...!" 

      - name: Configure Git Access
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Modify Manifests
        run: |
          sed -i "s|ed358/web-app:v[0-9]+\.[0-9]+\.[0-9]+$|ed358/web-app:${{ needs.setTag.outputs.tag }}|" deployment.yaml 
          sed -i "s|<p>[[:space:]]*version: v[0-9]+\.[0-9]+\.[0-9]+[[:space:]]*</p>|<p>${{ needs.setTag.outputs.tag }}</p>|" web-app/index.php
          cat deployment.yaml
          cat web-app/index.php
          git add deployment.yaml
          git commit -m "Update Docker image version in deployment.yaml"
          git push
